[package]
name = "mlua-luau-runtime"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib/lib.rs"

[dependencies]
async-executor = "1.8"
concurrent-queue = "2.4"
event-listener = "4.0"
futures-lite = "2.2"

mlua = { version = "0.9.5", features = [
    "luau",
    "luau-jit",
    "async",
    "serialize",
] }

[dev-dependencies]
async-fs = "2.1"
async-io = "2.3"

[[example]]
name = "basic_sleep"
test = true

[[example]]
name = "basic_spawn"
test = true

[[example]]
name = "callbacks"
test = true

[[example]]
name = "lots_of_threads"
test = true

[[example]]
name = "scheduler_ordering"
test = true
