[package]
name = "smol-mlua"
version = "0.0.0"
edition = "2021"

[dependencies]
smol = "2.0"
mlua = { version = "0.9", features = ["luau", "luau-jit", "async"] }

[lib]
path = "lib/lib.rs"

[examples]
basic-sleep = "examples/basic_sleep.rs"
basic-spawn = "examples/basic_spawn.rs"
callbacks = "examples/callbacks.rs"
captures = "examples/captures.rs"
lots-of-threads = "examples/lots_of_threads.rs"
scheduler-ordering = "examples/scheduler_ordering.rs"
