[package]
name = "luau-scheduler-experiments"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
mlua = { version = "0.9", features = ["luau", "luau-jit"] }
